2025-03-19 05:53:47,682 INFO    StreamThr :24628 [internal.py:wandb_internal():85] W&B internal server running at pid: 24628, started at: 2025-03-19 05:53:47.681760
2025-03-19 05:53:47,683 DEBUG   HandlerThread:24628 [handler.py:handle_request():158] handle_request: status
2025-03-19 05:53:47,684 INFO    WriterThread:24628 [datastore.py:open_for_write():87] open: /home/khanhtl/Code/FL/CNN_Model/wandb/run-20250319_055347-leja8pt0/run-leja8pt0.wandb
2025-03-19 05:53:47,684 DEBUG   SenderThread:24628 [sender.py:send():391] send: header
2025-03-19 05:53:47,686 DEBUG   SenderThread:24628 [sender.py:send():391] send: run
2025-03-19 05:53:53,344 INFO    SenderThread:24628 [dir_watcher.py:__init__():211] watching files in: /home/khanhtl/Code/FL/CNN_Model/wandb/run-20250319_055347-leja8pt0/files
2025-03-19 05:53:53,344 INFO    SenderThread:24628 [sender.py:_start_run_threads():1200] run started: leja8pt0 with start time 1742338427.681482
2025-03-19 05:53:53,344 DEBUG   HandlerThread:24628 [handler.py:handle_request():158] handle_request: status_report
2025-03-19 05:53:53,354 DEBUG   HandlerThread:24628 [handler.py:handle_request():158] handle_request: run_start
2025-03-19 05:53:53,364 DEBUG   HandlerThread:24628 [system_info.py:__init__():26] System info init
2025-03-19 05:53:53,364 DEBUG   HandlerThread:24628 [system_info.py:__init__():41] System info init done
2025-03-19 05:53:53,364 INFO    HandlerThread:24628 [system_monitor.py:start():194] Starting system monitor
2025-03-19 05:53:53,364 INFO    SystemMonitor:24628 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-03-19 05:53:53,364 INFO    HandlerThread:24628 [system_monitor.py:probe():214] Collecting system info
2025-03-19 05:53:53,365 INFO    SystemMonitor:24628 [interfaces.py:start():188] Started cpu monitoring
2025-03-19 05:53:53,365 INFO    SystemMonitor:24628 [interfaces.py:start():188] Started disk monitoring
2025-03-19 05:53:53,365 INFO    SystemMonitor:24628 [interfaces.py:start():188] Started gpu monitoring
2025-03-19 05:53:53,366 INFO    SystemMonitor:24628 [interfaces.py:start():188] Started memory monitoring
2025-03-19 05:53:53,366 INFO    SystemMonitor:24628 [interfaces.py:start():188] Started network monitoring
2025-03-19 05:53:53,374 DEBUG   HandlerThread:24628 [system_info.py:probe():152] Probing system
2025-03-19 05:53:53,376 DEBUG   HandlerThread:24628 [system_info.py:_probe_git():137] Probing git
2025-03-19 05:53:53,380 DEBUG   HandlerThread:24628 [system_info.py:_probe_git():145] Probing git done
2025-03-19 05:53:53,380 DEBUG   HandlerThread:24628 [system_info.py:probe():200] Probing system done
2025-03-19 05:53:53,380 DEBUG   HandlerThread:24628 [system_monitor.py:probe():223] {'os': 'Linux-6.11.0-19-generic-x86_64-with-glibc2.39', 'python': '3.12.7', 'heartbeatAt': '2025-03-18T22:53:53.374265', 'startedAt': '2025-03-18T22:53:47.678847', 'docker': None, 'cuda': None, 'args': ('--app', '.', '--num-supernodes', '20', '--backend-config', '{"client-resources": {"num-cpus": 1.0, "num-gpus": 1.0}}'), 'state': 'running', 'program': '/home/khanhtl/miniconda3/envs/FL/bin/flower-simulation', 'codePathLocal': None, 'git': {'remote': 'https://github.com/khanh22010449/CNN_Model.git', 'commit': '7b79d5a78a629e4b9c51cf6c1797317c8bceb629'}, 'email': '22010449@st.phenikaa-uni.edu.vn', 'root': '/home/khanhtl/Code/FL/CNN_Model', 'host': 'khanhtl', 'username': 'khanhtl', 'executable': '/home/khanhtl/miniconda3/envs/FL/bin/python3.12', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 4409.581875, 'min': 400.0, 'max': 4785.0}, 'cpu_freq_per_core': [{'current': 4437.601, 'min': 400.0, 'max': 4785.0}, {'current': 4440.441, 'min': 400.0, 'max': 4785.0}, {'current': 4438.824, 'min': 400.0, 'max': 4785.0}, {'current': 4441.778, 'min': 400.0, 'max': 4785.0}, {'current': 3404.752, 'min': 400.0, 'max': 4785.0}, {'current': 4406.877, 'min': 400.0, 'max': 4785.0}, {'current': 4438.006, 'min': 400.0, 'max': 4785.0}, {'current': 4410.105, 'min': 400.0, 'max': 4785.0}, {'current': 3731.36, 'min': 400.0, 'max': 4785.0}, {'current': 4406.855, 'min': 400.0, 'max': 4785.0}, {'current': 4422.545, 'min': 400.0, 'max': 4785.0}, {'current': 4434.273, 'min': 400.0, 'max': 4785.0}, {'current': 2927.107, 'min': 400.0, 'max': 4785.0}, {'current': 4406.899, 'min': 400.0, 'max': 4785.0}, {'current': 2949.384, 'min': 400.0, 'max': 4785.0}, {'current': 4406.864, 'min': 400.0, 'max': 4785.0}], 'disk': {'/': {'total': 182.2811393737793, 'used': 149.96245956420898}}, 'gpu': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 22.76729965209961}}
2025-03-19 05:53:53,380 INFO    HandlerThread:24628 [system_monitor.py:probe():224] Finished collecting system info
2025-03-19 05:53:53,380 INFO    HandlerThread:24628 [system_monitor.py:probe():227] Publishing system info
2025-03-19 05:53:53,380 DEBUG   HandlerThread:24628 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2025-03-19 05:53:53,380 ERROR   HandlerThread:24628 [system_info.py:_save_conda():223] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/site-packages/wandb/sdk/internal/system/system_info.py", line 216, in _save_conda
    subprocess.call(
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/khanhtl/miniconda3/envs/FL/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2025-03-19 05:53:53,381 DEBUG   HandlerThread:24628 [system_info.py:_save_conda():224] Saving conda packages done
2025-03-19 05:53:53,381 INFO    HandlerThread:24628 [system_monitor.py:probe():229] Finished publishing system info
2025-03-19 05:53:53,382 DEBUG   SenderThread:24628 [sender.py:send():391] send: files
2025-03-19 05:53:53,383 INFO    SenderThread:24628 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2025-03-19 05:53:53,455 DEBUG   HandlerThread:24628 [handler.py:handle_request():158] handle_request: python_packages
2025-03-19 05:53:53,456 DEBUG   SenderThread:24628 [sender.py:send_request():418] send_request: python_packages
2025-03-19 05:53:53,496 DEBUG   HandlerThread:24628 [handler.py:handle_request():158] handle_request: stop_status
2025-03-19 05:53:53,496 DEBUG   HandlerThread:24628 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-19 05:53:53,498 DEBUG   SenderThread:24628 [sender.py:send_request():418] send_request: stop_status
2025-03-19 05:53:54,065 DEBUG   SenderThread:24628 [sender.py:send():391] send: telemetry
2025-03-19 05:53:54,345 INFO    Thread-12 :24628 [dir_watcher.py:_on_file_created():271] file/dir created: /home/khanhtl/Code/FL/CNN_Model/wandb/run-20250319_055347-leja8pt0/files/requirements.txt
2025-03-19 05:53:54,345 INFO    Thread-12 :24628 [dir_watcher.py:_on_file_created():271] file/dir created: /home/khanhtl/Code/FL/CNN_Model/wandb/run-20250319_055347-leja8pt0/files/output.log
2025-03-19 05:53:54,345 INFO    Thread-12 :24628 [dir_watcher.py:_on_file_created():271] file/dir created: /home/khanhtl/Code/FL/CNN_Model/wandb/run-20250319_055347-leja8pt0/files/wandb-metadata.json
2025-03-19 05:53:54,345 INFO    Thread-12 :24628 [dir_watcher.py:_on_file_created():271] file/dir created: /home/khanhtl/Code/FL/CNN_Model/wandb/run-20250319_055347-leja8pt0/files/conda-environment.yaml
2025-03-19 05:53:54,442 INFO    wandb-upload_0:24628 [upload_job.py:push():130] Uploaded file /tmp/tmp0s3jx_dkwandb/4jrycsw3-wandb-metadata.json
2025-03-19 05:53:56,345 INFO    Thread-12 :24628 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_Model/wandb/run-20250319_055347-leja8pt0/files/output.log
2025-03-19 05:53:57,785 DEBUG   HandlerThread:24628 [handler.py:handle_request():158] handle_request: partial_history
2025-03-19 05:53:57,846 DEBUG   SenderThread:24628 [sender.py:send():391] send: telemetry
2025-03-19 05:53:58,345 INFO    Thread-12 :24628 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_Model/wandb/run-20250319_055347-leja8pt0/files/output.log
2025-03-19 05:53:58,412 DEBUG   HandlerThread:24628 [handler.py:handle_request():158] handle_request: status_report
2025-03-19 05:53:58,750 DEBUG   HandlerThread:24628 [handler.py:handle_request():158] handle_request: partial_history
2025-03-19 05:53:58,872 DEBUG   SenderThread:24628 [sender.py:send():391] send: history
2025-03-19 05:53:58,872 DEBUG   SenderThread:24628 [sender.py:send_request():418] send_request: summary_record
2025-03-19 05:53:58,874 INFO    SenderThread:24628 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2025-03-19 05:53:59,348 INFO    Thread-12 :24628 [dir_watcher.py:_on_file_created():271] file/dir created: /home/khanhtl/Code/FL/CNN_Model/wandb/run-20250319_055347-leja8pt0/files/wandb-summary.json
2025-03-19 05:54:00,459 INFO    Thread-12 :24628 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/khanhtl/Code/FL/CNN_Model/wandb/run-20250319_055347-leja8pt0/files/output.log
2025-03-19 05:54:01,369 INFO    cpu       :24628 [interfaces.py:monitor():138] Process cpu has exited.
2025-03-19 05:54:01,370 DEBUG   SystemMonitor:24628 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-03-19 05:54:01,370 DEBUG   SystemMonitor:24628 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-03-19 05:54:01,370 DEBUG   SystemMonitor:24628 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-03-19 05:54:01,371 DEBUG   SenderThread:24628 [sender.py:send():391] send: stats
2025-03-19 05:54:01,376 INFO    memory    :24628 [interfaces.py:monitor():138] Process proc.memory.rssMB has exited.
2025-03-19 05:54:01,455 INFO    MainThread:24628 [internal.py:handle_exit():75] Internal process exited
